# Generated by Django 5.2.17 on 2026-09-28 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hopitaux'),
        ('patients', '0004_alter_patient_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='accounts.hospital', verbose_name='hôpital'),
        ),
    ]
