# Generated by Django 5.2.17 on 2026-09-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_numeros_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antecedents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
