# Generated by Django 5.2.17 on 2026-09-26 02:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescriptions', '0002_prescription_consultation_prescription_prepared_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Médicament', 'Médicament'), ('Consommable', 'Consommable'), ('Laboratoire', 'Laboratoire')], max_length=30)),
                ('therapeutic_class', models.CharField(blank=True, help_text='Ex. Antalgique (Pharmacie).', max_length=80)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('unit', models.CharField(default='Boîte', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('products_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stock_after', models.PositiveIntegerField()),
                ('motif', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('document_reference', models.CharField(blank=True, max_length=60)),
                ('service', models.CharField(blank=True, max_length=80)),
                ('patient', models.CharField(blank=True, max_length=150)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='prescriptions.prescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stocks.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
