# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'mouvement de stock', 'verbose_name_plural': 'mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'produit', 'verbose_name_plural': 'produits'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['id'], 'verbose_name': 'fournisseur', 'verbose_name_plural': 'fournisseurs'},
        ),
    ]
