# Generated by Django 5.2.17 on 2026-10-01 21:48

import django.db.models.deletion
from django.db import migrations, models


def rattacher(apps, schema_editor):
    """Les produits et fournisseurs existants appartiennent au premier hôpital (MA SANTÉ)."""
    Hospital = apps.get_model("accounts", "Hospital")
    premier = Hospital.objects.filter(active=True).order_by("pk").first()
    if premier:
        for nom in ("Product", "Supplier"):
            apps.get_model("stocks", nom).objects.filter(hospital__isnull=True).update(hospital=premier)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('stocks', '0002_alter_movement_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.RunPython(rattacher, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='stocks_produit_unique_par_hopital'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='stocks_fournisseur_unique_par_hopital'),
        ),
    ]
