# Generated by Django 5.2.17 on 2026-09-26 01:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.PositiveSmallIntegerField(help_text='Conformité en %.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('compliant', models.BooleanField(default=True)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HygieneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(choices=[('FlaskConical', 'FlaskConical'), ('LockKeyhole', 'LockKeyhole'), ('ShieldCheck', 'ShieldCheck'), ('Biohazard', 'Biohazard'), ('Package', 'Package')], default='Package', max_length=30)),
                ('last_check', models.DateField(help_text='Dernier contrôle de disponibilité.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Déchets infectieux', 'Déchets infectieux'), ('Déchets chimiques', 'Déchets chimiques'), ('Déchets assimilés', 'Déchets assimilés')], max_length=40)),
                ('quantity_kg', models.DecimalField(decimal_places=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Nettoyage', 'Nettoyage'), ('Désinfection', 'Désinfection'), ('Décontamination', 'Décontamination'), ('Stérilisation', 'Stérilisation')], default='Nettoyage', max_length=30)),
                ('responsible', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('status', models.CharField(choices=[('Planifiée', 'Planifiée'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='Planifiée', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'hour', 'id'],
            },
        ),
    ]
