# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningtask',
            options={'ordering': ['-date', 'hour', 'id'], 'verbose_name': "tâche d'hygiène", 'verbose_name_plural': "tâches d'hygiène"},
        ),
        migrations.AlterModelOptions(
            name='hygieneaudit',
            options={'ordering': ['-date', '-id'], 'verbose_name': "contrôle d'hygiène", 'verbose_name_plural': "contrôles d'hygiène"},
        ),
        migrations.AlterModelOptions(
            name='hygieneproduct',
            options={'ordering': ['name'], 'verbose_name': "produit d'hygiène", 'verbose_name_plural': "produits d'hygiène"},
        ),
        migrations.AlterModelOptions(
            name='wastecollection',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'collecte de déchets', 'verbose_name_plural': 'collectes de déchets'},
        ),
    ]
