# Generated by Django 5.2.17 on 2026-10-01 21:50

import django.db.models.deletion
from django.db import migrations, models


def rattacher(apps, schema_editor):
    """Les données existantes appartiennent au premier hôpital (MA SANTÉ)."""
    Hospital = apps.get_model("accounts", "Hospital")
    premier = Hospital.objects.filter(active=True).order_by("pk").first()
    if premier:
        for nom in ['CleaningTask', 'HygieneProduct', 'WasteCollection', 'HygieneAudit']:
            apps.get_model("hygiene", nom).objects.filter(hospital__isnull=True).update(hospital=premier)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('hygiene', '0002_alter_cleaningtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='hygieneaudit',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='hygieneproduct',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.RunPython(rattacher, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hygieneproduct',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='hygieneproduct',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='hygiene_produit_unique_par_hopital'),
        ),
    ]
