# Generated by Django 5.2.17 on 2026-09-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_roles_supplementaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTOR', 'Directeur de clinique'), ('DOCTOR', 'Médecin'), ('NURSE', 'Infirmier/infirmière'), ('RECEPTION', 'Réceptionniste'), ('LAB', 'Laborantin'), ('PHARMACY', 'Pharmacien'), ('ACCOUNTING', 'Comptable'), ('STOCK', 'Responsable des stocks'), ('HR', 'Responsable RH'), ('MAINTENANCE', 'Responsable maintenance'), ('REGISSEUR', 'Régisseur')], default='RECEPTION', max_length=30),
        ),
    ]
