# Generated by Django 5.2.17 on 2026-09-28 00:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_caisse_sessions_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name="nom de l'hôpital")),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Trois lettres majuscules.')], verbose_name='code')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='quartier')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='adresse')),
                ('slogan', models.CharField(blank=True, max_length=160)),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='devise')),
                ('license_number', models.CharField(blank=True, max_length=80, verbose_name="numéro d'agrément")),
                ('opening_hours', models.CharField(blank=True, default='24h/24 – 7j/7', max_length=160, verbose_name="horaires d'ouverture")),
                ('ticket_copies', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='souches par ticket')),
                ('ticket_validity_days', models.PositiveSmallIntegerField(default=15, help_text='Délai avant de pouvoir réémettre un ticket pour la même consultation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name="validité d'un reçu (jours)")),
                ('ticket_note', models.CharField(blank=True, default='Conservez ce reçu, il vous sera demandé en cas de réclamation.', max_length=200, verbose_name='mention en pied de ticket')),
                ('ticket_exclusions', models.CharField(blank=True, default='Laboratoire – Échographie – Hospitalisation', max_length=200, verbose_name='exclusions du ticket')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hôpital',
                'verbose_name_plural': 'hôpitaux',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.hospital', verbose_name='hôpital'),
        ),
    ]
