# Generated by Django 5.2.17 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hopital_par_defaut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
