# Generated by Django 5.2.17 on 2026-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_aide_soignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.TextField(blank=True, verbose_name='logo'),
        ),
    ]
