# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_consultation_prescription_prepared_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'ordonnance', 'verbose_name_plural': 'ordonnances'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'verbose_name': 'médicament prescrit', 'verbose_name_plural': 'médicaments prescrits'},
        ),
    ]
