# Generated by Django 5.2.17 on 2026-09-24 13:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0002_seed_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='sent_to_consultation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vitals', to='parcours.admission')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
