# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0003_soins_infirmiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'passage en caisse', 'verbose_name_plural': 'passages en caisse'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['id'], 'verbose_name': 'assurance', 'verbose_name_plural': 'assurances'},
        ),
        migrations.AlterModelOptions(
            name='medicalservice',
            options={'ordering': ['id'], 'verbose_name': 'service médical', 'verbose_name_plural': 'services médicaux'},
        ),
        migrations.AlterModelOptions(
            name='vitalsigns',
            options={'ordering': ['-recorded_at', '-id'], 'verbose_name': 'prise de constantes', 'verbose_name_plural': 'prises de constantes'},
        ),
    ]
