# Generated by Django 5.2.17 on 2026-09-26 22:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

EXAMENS = {"Échographie", "Radiographie", "Électrocardiogramme (ECG)"}
SOINS = {"Soins infirmiers", "Pansement", "Injection", "Vaccination", "Kinésithérapie", "Petite chirurgie"}


def reprise(apps, schema_editor):
    """Les passages déjà enregistrés l'étaient comme payés : on le rend explicite."""
    Admission = apps.get_model("parcours", "Admission")
    MedicalService = apps.get_model("parcours", "MedicalService")
    for admission in Admission.objects.all():
        admission.payment_status = "paye"
        admission.paid_at = admission.created_at
        admission.reference = f"TCK-{admission.created_at:%Y}-{admission.pk:06d}"
        admission.save(update_fields=["payment_status", "paid_at", "reference"])
    MedicalService.objects.filter(name__in=EXAMENS).update(category="EXAMEN")
    MedicalService.objects.filter(name__in=SOINS).update(category="SOIN")



class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0005_prestations_courantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_status',
            field=models.CharField(choices=[('en_attente', 'À payer'), ('paye', 'Payé'), ('assurance', 'Pris en charge (100 %)')], default='en_attente', max_length=20, verbose_name='paiement'),
        ),
        migrations.AddField(
            model_name='admission',
            name='printed_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admission',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='n° de ticket'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='category',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('SOIN', 'Soin'), ('EXAMEN', 'Examen')], default='CONSULTATION', max_length=20, verbose_name='catégorie'),
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_attente', 'En attente de validation'), ('validee', 'Validée')], default='ouverte', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='montant attendu')),
                ('counted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant compté')),
                ('gap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='écart')),
                ('justification', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('received', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant reçu')),
                ('validation_gap', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='écart à la validation')),
                ('validation_note', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_parcours', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session de caisse',
                'verbose_name_plural': 'sessions de caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='parcours.cashsession'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ouverte')), fields=('cashier',), name='parcours_une_caisse_ouverte'),
        ),
        migrations.RunPython(reprise, migrations.RunPython.noop),
    ]
