# Generated by Django 5.2.17 on 2026-09-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0006_caisse_sessions_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'service de destination',
                'verbose_name_plural': 'services de destination',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observations'),
        ),
        migrations.AddField(
            model_name='admission',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantité'),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='parcours.department', verbose_name='service de destination'),
        ),
    ]
