# Generated by Django 5.2.17 on 2026-09-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0008_repartition_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant reçu'),
        ),
    ]
