# Generated by Django 5.2.17 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0010_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='specialite',
            field=models.CharField(blank=True, max_length=40, verbose_name='spécialité'),
        ),
    ]
