# Generated by Django 5.2.17 on 2026-09-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_specialites'),
        ('parcours', '0012_specialites_des_prestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservice',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='medicalservice',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='parcours_prestation_unique_par_hopital'),
        ),
    ]
