# Generated by Django 5.2.17 on 2026-09-30 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours', '0014_catalogue_par_hopital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=600, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement push du personnel',
                'verbose_name_plural': 'abonnements push du personnel',
            },
        ),
        migrations.CreateModel(
            name='EtatNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vues', models.JSONField(blank=True, default=dict)),
                ('envoyees', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etat_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'état des notifications',
                'verbose_name_plural': 'états des notifications',
            },
        ),
    ]
