# Generated by Django 5.2.17 on 2026-09-20 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0002_patient_city_patient_emergency_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('EXAM', 'Examen'), ('CARE', 'Soin'), ('STAY', 'Hospitalisation'), ('OTHER', 'Autre')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('covered', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ma Santé', max_length=160)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('legal_info', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('submitted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('insurance_snapshot', models.JSONField(default=dict)),
                ('clinic_snapshot', models.JSONField(default=dict)),
                ('patient_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('insurance_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coverage_confirmed_at', models.DateTimeField(null=True)),
                ('claim_status', models.CharField(choices=[('DUE', 'À transmettre'), ('SENT', 'Transmis'), ('DISPUTED', 'Contesté'), ('PARTIAL', 'Partiellement réglé'), ('PAID', 'Réglé')], default='DUE', max_length=15)),
                ('claim_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_bill', to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('insurance_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('patient_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.benefit')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='cashdesk.bill')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.invoiceitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.service')),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('lines', models.JSONField(default=list)),
                ('patient_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('insurance_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='cashdesk.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='cash_insurance_rate')],
            },
        ),
        migrations.CreateModel(
            name='ClaimBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('snapshot', models.JSONField(default=list)),
                ('supporting_reference', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bills', models.ManyToManyField(related_name='batches', to='cashdesk.bill')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.insurance')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashdesk.insurance'),
        ),
        migrations.CreateModel(
            name='PatientCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=100)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('holder', models.CharField(blank=True, max_length=180)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.insurance')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coverage', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('payer', models.CharField(choices=[('PATIENT', 'Patient'), ('INSURANCE', 'Assurance')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tendered', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile Money'), ('CARD', 'Carte'), ('TRANSFER', 'Virement')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashdesk.bill')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cashdesk.billline')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cashdesk.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE', 'Mobile Money'), ('CARD', 'Carte'), ('TRANSFER', 'Virement')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='cashdesk.payment')),
            ],
        ),
        migrations.CreateModel(
            name='RefundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.billline')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='cashdesk.refund')),
            ],
        ),
        migrations.AddField(
            model_name='benefit',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.service'),
        ),
        migrations.CreateModel(
            name='ServiceQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('WAITING', 'En attente'), ('RECEIVED', 'Reçu'), ('DONE', 'Terminé'), ('CANCELLED', 'Annulé')], default='WAITING', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entry', to='cashdesk.billline')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'À valider'), ('VALIDATED', 'Validée')], default='OPEN', max_length=12)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('closed_snapshot', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField(null=True)),
                ('received_cash', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('validation_note', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='refund',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='cashdesk.session'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cashdesk.session'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('IN', 'Apport'), ('OUT', 'Sortie'), ('HANDOVER', 'Versement intermédiaire')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cashdesk.session')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='cashdesk.visit'),
        ),
        migrations.CreateModel(
            name='CoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cashdesk.benefit')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='cashdesk.insurance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('insurance', 'benefit'), name='cash_coverage_unique'), models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='cash_rule_rate')],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'key'), name='cash_operation_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='benefit',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='cash_benefit_price'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cashier',), name='cash_one_open_session'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('opening_float__gte', 0)), name='cash_positive_float'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('mode', 'CASH'), _negated=True), fields=('mode', 'reference'), name='cash_electronic_reference'),
        ),
    ]
