# Generated by Django 5.2.17 on 2026-09-24 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('parcours', '0003_soins_infirmiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='parcours.admission'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
