# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_admission_consultation_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_time'], 'verbose_name': 'consultation', 'verbose_name_plural': 'consultations'},
        ),
    ]
