# Generated by Django 5.2.17 on 2026-09-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_consultation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_trace',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultation',
            name='completed_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='current_step',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultation',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consultation',
            name='outcome',
            field=models.CharField(blank=True, choices=[('sortie', 'Retour à domicile'), ('rdv', 'Rendez-vous de contrôle'), ('observation', 'Mise en observation'), ('hospitalisation', 'Hospitalisation'), ('refere_interne', 'Référé en interne'), ('refere_externe', 'Référé en externe'), ('refus', "Refus d'hospitalisation"), ('evade', 'Évadé'), ('decede', 'Décédé')], max_length=30, verbose_name='issue'),
        ),
    ]
