# Generated by Django 5.2.17 on 2026-09-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_medecine_generale'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ia_echange_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='ia_messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
