# Generated by Django 5.2.17 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_conversation_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='specialite',
            field=models.CharField(default='medecine-generale', max_length=40, verbose_name='spécialité'),
        ),
    ]
