# Generated by Django 5.2.17 on 2026-09-26 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalization', '0001_initial'),
        ('parcours', '0003_soins_infirmiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='parcours.admission'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='planned_discharge',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='service',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(default='Standard', max_length=40),
        ),
    ]
