# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalization', '0002_parcours_sejour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'verbose_name': 'lit', 'verbose_name_plural': 'lits'},
        ),
        migrations.AlterModelOptions(
            name='hospitalization',
            options={'verbose_name': 'séjour', 'verbose_name_plural': 'séjours'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'chambre', 'verbose_name_plural': 'chambres'},
        ),
    ]
