# Generated by Django 5.2.17 on 2026-10-01 12:36

import django.db.models.deletion
from django.db import migrations, models


def rattacher(apps, schema_editor):
    """Les chambres existantes appartiennent au premier hôpital (celui d'avant le multi-hôpitaux)."""
    Room = apps.get_model("hospitalization", "Room")
    Hospital = apps.get_model("accounts", "Hospital")
    premier = Hospital.objects.order_by("pk").first()
    if premier:
        Room.objects.filter(hospital__isnull=True).update(hospital=premier)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_role_aide_soignant'),
        ('hospitalization', '0003_alter_bed_options_alter_hospitalization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.RunPython(rattacher, migrations.RunPython.noop),
    ]
