# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forminstance',
            options={'verbose_name': 'formulaire', 'verbose_name_plural': 'formulaires'},
        ),
    ]
