# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'facture', 'verbose_name_plural': 'factures'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'ligne de facture', 'verbose_name_plural': 'lignes de facture'},
        ),
    ]
