# Generated by Django 5.2.17 on 2026-09-26 01:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Électricité', 'Électricité'), ('Climatisation', 'Climatisation'), ('Stérilisation', 'Stérilisation'), ('Froid médical', 'Froid médical'), ('Gaz médicaux', 'Gaz médicaux'), ('Infrastructure', 'Infrastructure')], max_length=40)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('availability', models.PositiveSmallIntegerField(default=100, help_text='Disponibilité constatée, en %.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maintenance_interval_days', models.PositiveSmallIntegerField(default=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Préventive', 'Préventive'), ('Corrective', 'Corrective')], default='Préventive', max_length=20)),
                ('priority', models.CharField(choices=[('Normale', 'Normale'), ('Haute', 'Haute'), ('Critique', 'Critique')], default='Normale', max_length=20)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En attente', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='maintenance.equipment')),
            ],
            options={
                'ordering': ['-date', '-time', '-id'],
            },
        ),
    ]
