# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'équipement', 'verbose_name_plural': 'équipements'},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'intervention', 'verbose_name_plural': 'interventions'},
        ),
    ]
