# Generated by Django 5.2.17 on 2026-09-29 15:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



def remplir(apps, schema_editor):
    """Équipements existants : un jeton chacun, un code interne, et l'hôpital par défaut."""
    Equipment = apps.get_model("maintenance", "Equipment")
    Hospital = apps.get_model("accounts", "Hospital")
    default = Hospital.objects.order_by("pk").first()
    counters = {}
    for equipment in Equipment.objects.order_by("pk"):
        equipment.qr_token = uuid.uuid4()
        equipment.hospital = equipment.hospital or default
        if equipment.hospital and not equipment.code:
            code = equipment.hospital.code
            counters[code] = counters.get(code, 0) + 1
            equipment.code = f"EQ-{code}-{counters[code]:04d}"
        equipment.save(update_fields=["qr_token", "hospital", "code"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hopital_par_defaut'),
        ('maintenance', '0002_alter_equipment_options_alter_intervention_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "scan d'équipement",
                'verbose_name_plural': "scans d'équipements",
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='acquisition',
            field=models.CharField(blank=True, choices=[('Achat', 'Achat'), ('Don', 'Don'), ("Dotation de l'État", "Dotation de l'État"), ('Location', 'Location'), ('Prêt', 'Prêt')], max_length=30, verbose_name="mode d'acquisition"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='marque'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='code interne'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name="date d'installation"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modèle'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='qr_token',
            field=models.UUIDField(editable=False, null=True, verbose_name='jeton du QR code'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numéro de série'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service',
            field=models.CharField(blank=True, max_length=120, verbose_name='service'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('En service', 'En service'), ('En panne', 'En panne'), ('Réformé', 'Réformé')], default='En service', max_length=20, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, help_text="Fournisseur, donateur ou organisme qui a envoyé l'appareil.", max_length=160, verbose_name="structure d'origine"),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_end',
            field=models.DateField(blank=True, null=True, verbose_name='fin de garantie'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='company',
            field=models.CharField(blank=True, max_length=160, verbose_name='entreprise'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coût'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='diagnostic'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (minutes)'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='parts',
            field=models.TextField(blank=True, verbose_name='pièces remplacées'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='technician_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_interventions', to=settings.AUTH_USER_MODEL, verbose_name='technicien (compte)'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='work_done',
            field=models.TextField(blank=True, verbose_name='travaux réalisés'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('Électricité', 'Électricité'), ('Climatisation', 'Climatisation'), ('Stérilisation', 'Stérilisation'), ('Froid médical', 'Froid médical'), ('Gaz médicaux', 'Gaz médicaux'), ('Infrastructure', 'Infrastructure'), ('Imagerie médicale', 'Imagerie médicale'), ('Laboratoire', 'Laboratoire'), ('Monitoring', 'Monitoring'), ('Bloc opératoire', 'Bloc opératoire'), ('Mobilier médical', 'Mobilier médical'), ('Informatique', 'Informatique')], max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='maintenance_equipement_unique_par_hopital'),
        ),
        migrations.AddField(
            model_name='equipmentscan',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='maintenance.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentscan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(remplir, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipment',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='jeton du QR code'),
        ),
    ]
