# Generated by Django 5.2.17 on 2026-10-01 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('portail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120)),
                ('texte', models.TextField(max_length=1000)),
                ('jusqu_au', models.DateField(blank=True, null=True)),
                ('retiree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envoyees', models.PositiveIntegerField(default=0, verbose_name='notifications envoyées')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces_patients', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'annonce aux patients',
                'verbose_name_plural': 'annonces aux patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
