# Generated by Django 5.2.17 on 2026-09-29 14:02

import django.db.models.deletion
import ged.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_hopital_par_defaut'),
        ('patients', '0007_medecine_generale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentiteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenoms', models.CharField(blank=True, max_length=180)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('annee_naissance', models.PositiveSmallIntegerField(blank=True, help_text="Quand seule l'année est connue.", null=True)),
                ('numero_registre', models.CharField(blank=True, max_length=60, verbose_name='n° dans le registre')),
                ('annee_registre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année du registre')),
                ('service', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identites_archive', to='patients.patient', verbose_name='dossier actuel')),
            ],
            options={
                'verbose_name': "identité d'archive",
                'verbose_name_plural': "identités d'archive",
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('registre', 'Registre papier'), ('dossier', 'Dossier médical'), ('compte_rendu', 'Compte rendu'), ('ordonnance', 'Ordonnance'), ('laboratoire', 'Résultat de laboratoire'), ('imagerie', 'Imagerie'), ('administratif', 'Pièce administrative'), ('facture', 'Facture'), ('courrier', 'Courrier'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='date du document')),
                ('service', models.CharField(blank=True, max_length=120)),
                ('mots_cles', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stockage', models.CharField(choices=[('local', 'Serveur du centre'), ('distant', "Logiciel d'archivage")], default='local', max_length=10)),
                ('fichier', models.FileField(blank=True, upload_to=ged.models.chemin_fichier)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, verbose_name="nom d'origine")),
                ('taille', models.PositiveBigIntegerField(default=0)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('reference_distante', models.CharField(blank=True, help_text='Identifiant du document dans le logiciel externe.', max_length=255)),
                ('synchronisation', models.CharField(choices=[('local', 'Local seulement'), ('a_envoyer', 'À envoyer'), ('envoye', 'Envoyé'), ('erreur', "Échec d'envoi")], default='local', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_ged', to='patients.patient')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ged.identitearchive')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
