# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_catalogue_examens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labexam',
            options={'ordering': ['id'], 'verbose_name': 'examen', 'verbose_name_plural': 'examens'},
        ),
        migrations.AlterModelOptions(
            name='labrequest',
            options={'verbose_name': "demande d'analyse", 'verbose_name_plural': "demandes d'analyse"},
        ),
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['id'], 'verbose_name': "résultat d'analyse", 'verbose_name_plural': "résultats d'analyse"},
        ),
    ]
