# Generated by Django 5.2.17 on 2026-09-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Conservé même si le compte disparaît.', max_length=150, verbose_name='identifiant')),
                ('action', models.CharField(max_length=40)),
                ('module', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='navigateur')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée (ms)')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "entrée du journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MA SANTÉ', max_length=160, verbose_name="nom de l'établissement")),
                ('slogan', models.CharField(blank=True, default='Santé – Proximité – Confiance', max_length=160)),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='adresse')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='devise')),
                ('license_number', models.CharField(blank=True, max_length=80, verbose_name="numéro d'agrément")),
                ('opening_hours', models.CharField(blank=True, default='24h/24 – 7j/7', max_length=160, verbose_name="horaires d'ouverture")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paramètres généraux',
                'verbose_name_plural': 'paramètres généraux',
            },
        ),
    ]
