# Generated by Django 5.2.17 on 2026-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_audit_et_parametres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admindocument',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'document administratif', 'verbose_name_plural': 'documents administratifs'},
        ),
    ]
