# Generated by Django 5.2.17 on 2026-10-01 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('consultations', '0006_specialites'),
        ('patients', '0007_medecine_generale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('diagnostic', 'Diagnostic proposé'), ('examens', 'Examens proposés'), ('ordonnance', 'Ordonnance proposée'), ('conseils', 'Conseils proposés'), ('conversation', 'Question sur le patient')], max_length=20)),
                ('demande', models.TextField(blank=True, verbose_name='demande')),
                ('reponse', models.JSONField(default=dict, verbose_name="réponse de l'IA")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_ia', to='consultations.consultation')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions_ia', to='accounts.hospital', verbose_name='hôpital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions_ia', to='patients.patient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sollicitée par')),
            ],
            options={
                'verbose_name': "intervention de l'IA",
                'verbose_name_plural': "interventions de l'IA",
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['hospital', 'patient', '-created_at'], name='ia_interven_hospita_b74270_idx')],
            },
        ),
    ]
