# Generated by Django 5.2.17 on 2026-09-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('poste', models.CharField(max_length=120)),
                ('departement', models.CharField(max_length=120)),
                ('dateEmbauche', models.DateField()),
                ('contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Prestataire', 'Prestataire')], default='CDI', max_length=20)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Congé', 'Congé'), ('Suspendu', 'Suspendu'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
    ]
