# Generated by Django 5.2.17 on 2026-10-01 21:50

import django.db.models.deletion
from django.db import migrations, models


def rattacher(apps, schema_editor):
    """Les données existantes appartiennent au premier hôpital (MA SANTÉ)."""
    Hospital = apps.get_model("accounts", "Hospital")
    premier = Hospital.objects.filter(active=True).order_by("pk").first()
    if premier:
        for nom in ['Employee']:
            apps.get_model("rh", nom).objects.filter(hospital__isnull=True).update(hospital=premier)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('rh', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital', verbose_name='hôpital'),
        ),
        migrations.RunPython(rattacher, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='employee',
            name='matricule',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('hospital', 'matricule'), name='rh_matricule_unique_par_hopital'),
        ),
    ]
