# Generated by Django 5.2.17 on 2026-10-02 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_logo_hopital'),
        ('rh', '0003_par_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dateFinContrat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Congé annuel', 'Congé annuel'), ('Maladie', 'Maladie'), ('Maternité', 'Maternité'), ('Paternité', 'Paternité'), ('Formation', 'Formation'), ('Permission', 'Permission'), ('Absence injustifiée', 'Absence injustifiée')], default='Congé annuel', max_length=30)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='rh.employee')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'congés et absences',
                'ordering': ['-debut'],
            },
        ),
    ]
